# -*- coding: utf-8 -*-
"""feature_extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mGCFk6vujOgGLfOj41XifwnvLl0-JksX
"""

import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image
import numpy as np

class FeatureExtractor:
    def __init__(self):
        # Initialize ResNet50 with default pre-trained weights
        self.model = models.resnet50(weights='DEFAULT')

        # Remove the classification head (last layer) to get the 2048-dim feature vector
        # Source logic: self.backbone = torch.nn.Sequential(*(list(self.model.children())[:-1]))
        self.backbone = nn.Sequential(*(list(self.model.children())[:-1]))

        self.backbone.eval()

        # Standard ImageNet normalization
        self.preprocess = transforms.Compose([
            transforms.Resize(256),
            transforms.CenterCrop(224),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        ])

    def extract(self, img_path):
        """
        Takes an image path, preprocesses it, and returns a normalized numpy feature vector.
        """
        try:
            image = Image.open(img_path).convert('RGB')
            input_tensor = self.preprocess(image)
            input_batch = input_tensor.unsqueeze(0)  # Shape: [1, 3, 224, 224]

            with torch.no_grad():
                feature_vector = self.backbone(input_batch)

            # Flatten to [2048]
            return feature_vector.flatten().numpy()

        except Exception as e:
            print(f"Error processing {img_path}: {e}")
            return None