# -*- coding: utf-8 -*-
"""index_images.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mGCFk6vujOgGLfOj41XifwnvLl0-JksX
"""

import os
import pickle
import numpy as np
import faiss
from feature_extractor import FeatureExtractor

# Configuration
IMAGE_DIR = './data/images'
INDEX_FILE = './data/metadata/vector.index'
METADATA_FILE = './data/metadata/metadata.pkl'

def main():
    if not os.path.exists(IMAGE_DIR):
        os.makedirs(IMAGE_DIR)
        print(f"Directory {IMAGE_DIR} created. Please add images there before running.")
        return

    # Create metadata directory if it doesn't exist
    os.makedirs(os.path.dirname(INDEX_FILE), exist_ok=True)

    extractor = FeatureExtractor()
    feature_list = []
    file_names = []

    valid_images = [f for f in os.listdir(IMAGE_DIR) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
    print(f"Found {len(valid_images)} images. Starting extraction...")

    for i, filename in enumerate(valid_images):
        path = os.path.join(IMAGE_DIR, filename)
        vector = extractor.extract(path)

        if vector is not None:
            # Normalize vector for Cosine Similarity (Inner Product)
            # Source: faiss.normalize_L2(vector.reshape(1, -1))
            faiss.normalize_L2(vector.reshape(1, -1))

            feature_list.append(vector)
            file_names.append(filename)

        if (i + 1) % 10 == 0:
            print(f"Processed {i + 1} images...")

    if not feature_list:
        print("No features extracted. Check your image folder.")
        return

    # Convert to float32 numpy array for FAISS
    features = np.array(feature_list).astype('float32')

    # Build FAISS Index (Dimension 2048 for ResNet50)
    d = 2048
    index = faiss.IndexFlatIP(d) # Inner Product = Cosine Similarity (when normalized)
    index.add(features)

    print(f"Index built with {index.ntotal} vectors.")

    # Save Index and Metadata
    faiss.write_index(index, INDEX_FILE)
    with open(METADATA_FILE, "wb") as f:
        pickle.dump(file_names, f)

    print(f"Saved index to {INDEX_FILE}")
    print(f"Saved metadata to {METADATA_FILE}")

if __name__ == "__main__":
    main()