# -*- coding: utf-8 -*-
"""search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mGCFk6vujOgGLfOj41XifwnvLl0-JksX
"""

import sys
import os
import faiss
import pickle
import numpy as np
from feature_extractor import FeatureExtractor

# Configuration
INDEX_FILE = './data/metadata/vector.index'
METADATA_FILE = './data/metadata/metadata.pkl'

class SearchEngine:
    def __init__(self):
        # We reuse the FeatureExtractor class to ensure consistent preprocessing
        self.extractor = FeatureExtractor()

        # Load FAISS index
        if not os.path.exists(INDEX_FILE):
            raise FileNotFoundError(f"Index file not found at {INDEX_FILE}. Run index_images.py first.")

        self.index = faiss.read_index(INDEX_FILE)

        # Load Metadata
        with open(METADATA_FILE, 'rb') as f:
            self.metadata = pickle.load(f)

    def search(self, query_img_path, top_k=5):
        query_vector = self.extractor.extract(query_img_path)

        if query_vector is None:
            return None, None

        # Normalize query vector
        faiss.normalize_L2(query_vector.reshape(1, -1))

        # Perform Search
        distances, indices = self.index.search(np.array([query_vector]), top_k)
        return distances, indices

def main():
    if len(sys.argv) < 2:
        print("Usage: python src/search.py <path_to_query_image>")
        return

    query_path = sys.argv[1]

    try:
        engine = SearchEngine()
        print(f"\nSearching for similar images to: {query_path}")

        distances, indices = engine.search(query_path, top_k=5)

        print("\n--- RESULTS ---")
        for i, idx in enumerate(indices[0]):
            score = distances[0][i]
            # Handle case where index might be out of bounds (rare but possible with dynamic updates)
            if idx < len(engine.metadata):
                filename = engine.metadata[idx]
                print(f"Rank {i+1}: {filename} (Similarity: {score:.4f})")
            else:
                print(f"Rank {i+1}: Unknown Index {idx}")

    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    main()